services:

  libretranslate:
    container_name: libretranslate
    image: quay.io/pussthecatorg/libretranslate:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./api_keys.db:/libretranslate/api_keys.db"
      - "./suggestions.db:/libretranslate/suggestions.db"
